"""Adicionar campo active para model store

Revision ID: 7efa32994e4b
Revises: bd50ec2a5fe8
Create Date: 2022-01-18 22:51:08.644458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efa32994e4b'
down_revision = 'bd50ec2a5fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'active')
    # ### end Alembic commands ###
